# Generated by Django 5.0.2 on 2024-02-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_advertisement_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
